### ISSUE TITLE
feat(Makefile): add the assigne user on a pull request

### ISSUE THREAD

**Issue by rdphv** [genjsdev/genjs#5]
Add "a" argument with the Git username (or email ?)
https://github.com/genjsdev/genjs/blob/master/Makefile#L51

Arguments:
https://hub.github.com/hub-pull-request.1.html

**Comment by ohoareau** [comment]
Please use the custom target feature for that purpose, by, for instance, creating a `make pr-me`

by adding something like the following in the `./.genjs/root/vars.yml` (or `./.genjs/projects/xxx.yml`) :

``` 
...
vars:
    makefile:
        targets:
            pr-me: hub pull-request -b $(b) -a $(a)
```
